### PR TITLE
SFD-2355 - Terraform scripts for the creation of the Services Elasticsearch domain

### PR DESCRIPTION
**Pull request by jope1**
This PR contains the terraform scripts required to create and maintain the Services Elasticsearch domain.
The PR also contains bulk service data scripts and a new make target to load in (or refresh) the full set of services into a Services Elasticsearch domain (the exact elasticsearch domain is determined by the PROFILE.

### CODE REVIEW

**Comment by stefaniuk** [comment]
Do we have a make target for provisioning the ES stack?

**Review by stefaniuk — DISMISSED** [review]
It is just the make target that we need to edit. 

Looks good!

**Comment by jope1** [comment]
Provision make target updated with infrastructure stack of elasticsearch.

**Review by stefaniuk — APPROVED** [review]
👍

**Pull request merged**
