### PR TITLE
SFD-2837 Authentication layer

### PR DESCRIPTION
**Pull request by ArifNhs**
SFD 2837 authentication layer for fuzzy search api

### CODE REVIEW

**Comment by stefaniuk** [comment]
@ArifNhs PLease, can we change the title of this PR from "SFD 2837 authentication layer for fuzzy search API" to "SFD-2837 Add authentication layer"

**Review by stefaniuk — CHANGES_REQUESTED** [review]

**Review by stefaniuk — APPROVED** [review]
@ArifNhs and @gwaardenburg I've spoken to you about this PR on Friday. As agreed let's merge it if you both are happy. We'll refactor this component as a part of the effort we mentioned.

**Review by gwaardenburg — DISMISSED** [review]

**Review by gwaardenburg — DISMISSED** [review]

**Review by jope1 — CHANGES_REQUESTED** [review]
As discussed we will break this ticket down under SFD-3152.  We will not merge this PR but we will keep it as reference until we have completed 3152.

**Comment by jope1** [comment]
Closed as superceeded by https://github.com/nhsd-exeter/dos-service-fuzzy-search-api/pull/48 and https://github.com/nhsd-exeter/dos-service-fuzzy-search-api/pull/46 and https://github.com/nhsd-exeter/dos-service-fuzzy-search-api/pull/43 and https://github.com/nhsd-exeter/dos-service-fuzzy-search-api/pull/41

**Pull request closed without merging**
